[package]
name = "localstore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
walkdir = "2"
digest= "*"
sha2 = "0.10.8"
ring = "0.16"
hex ="0.4.3"